services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: false

  WechatMiniProgramCustomServiceBundle\Controller\:
    resource: '../../Controller/'

  WechatMiniProgramCustomServiceBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'

  WechatMiniProgramCustomServiceBundle\Repository\:
    resource: '../../Repository/'

  WechatMiniProgramCustomServiceBundle\Service\:
    resource: '../../Service/'
    public: true
